name: uFSM CI workflow
on: push
jobs:
  build:
    name: Build and run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./ci
    - name: configure
      run: |
        conan install . -if build
        cmake -G Ninja -S . -B ./build
    - name: build
      run: cmake --build ./build -- -j8
