name: uFSM CI workflow
on: push
jobs:
  build:
    name: Build and run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./ci/gcc
    - name: configure
      run: conan install . -if build
      run: cmake -G Ninja -S . -B ./build
    - name: make
      run: cmake --build ./build -- -j8
